### ISSUE TITLE
Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'

### ISSUE THREAD

**Issue by ghost** [jetstack/terraform-google-gke-cluster#21]
Error: Error applying plan:

1 error(s) occurred:

* module.cluster.google_container_cluster.cluster: 1 error(s) occurred:

* google_container_cluster.cluster: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by ghost** [comment]
Went into module and set region in the provider

**Comment by wwwil** [comment]
Thanks for submitting an issue, I have reopened it as I'd like to get it fixed! I get the same problem when using the example project.

I think this has come about as I removed the `region` and `zone` variables when switching to using `location` in the cluster definition, without considering that they were required elsewhere. This problem was not picked up by our CI either, which highlights another problem that we should address!
