### ISSUE TITLE
google_container_cluster.cluster: project: required field is not set

### ISSUE THREAD

**Issue by znat** [jetstack/terraform-google-gke-cluster#32]
Error: Error applying plan:

1 error occurred:
        * module.cluster.google_container_cluster.cluster: 1 error occurred:
        * google_container_cluster.cluster: project: required field is not set

Other issues seems to indicate that this is already fixed but it doesn't seem to be. Using 0.1.0-beta2.
In the `main.tf` of the module the google provider doesn't have neither project nor region:

```
provider "google" {
  version = "2.5.1"
}
```

**Comment by wwwil** [comment]
Hi! Thanks for your feedback 😄 

I assume you're using the latest Terraform Registry version? This problem should have been fixed by #23, however I've not tagged a new version since then, so that's my bad.

I'm going to tag a new version today, as soon as the new test script PR #29 is merged and passes!

**Comment by wwwil** [comment]
Just tagged a new version, which should resolve this https://github.com/jetstack/terraform-google-gke-cluster/releases/tag/v0.1.0. Please reopen the issue if there are still problems 😄
